# Generated by Django 4.0.5 on 2022-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0005_vacuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
